# Atualizar TARGET com nome do executavel a ser gerado na compilacao.
TARGET = main

# Atualizar SDL_DIR com o local onde SDL3 esta instalado.
# Uso da barra '\\' especifico para Windows.
SDL_DIR = C:\\SDL3
SDL_INC_DIR = $(SDL_DIR)\\include

# Arquitetura da biblioteca (x86, x64 ou arm64)
SDL_ARCH = x64
SDL_LIB_DIR = $(SDL_DIR)\\lib\\$(SDL_ARCH)
SDL_DLL_DIR = $(SDL_LIB_DIR)

# Atualizar SDL_IMAGE_DIR com o local onde SDL3_image esta instalado.
SDL_IMAGE_DIR = C:\\SDL3\\SDL3_image
SDL_IMAGE_INC_DIR = $(SDL_IMAGE_DIR)\\include
SDL_IMAGE_LIB_DIR = $(SDL_IMAGE_DIR)\\lib\\$(SDL_ARCH)
SDL_IMAGE_DLL_DIR = $(SDL_IMAGE_LIB_DIR)

# Atualizar SDL_TTF_DIR com o local onde SDL3_ttf esta instalado.
SDL_TTF_DIR = C:\\SDL3\\SDL3_ttf
SDL_TTF_INC_DIR = $(SDL_TTF_DIR)\\include
SDL_TTF_LIB_DIR = $(SDL_TTF_DIR)\\lib\\$(SDL_ARCH)
SDL_TTF_DLL_DIR = $(SDL_TTF_LIB_DIR)

SDL_DLL_FILE = SDL3.dll
SDL_IMAGE_DLL_FILE = SDL3_image.dll
SDL_TTF_DLL_FILE = SDL3_ttf.dll

CC = gcc
CFLAGS = -std=c23 -Wall -Wextra -Wpedantic -Wno-unused-result
LDFLAGS = -L$(SDL_LIB_DIR) -L$(SDL_IMAGE_LIB_DIR) -L$(SDL_TTF_LIB_DIR)
LDLIBS = -l:SDL3.lib -l:SDL3_image.lib -l:SDL3_ttf.lib
INC_DIRS = $(addprefix -I, $(SDL_INC_DIR) $(SDL_IMAGE_INC_DIR) $(SDL_TTF_INC_DIR))

# Incluir subdiretorio(s) em SUBDIR, caso exista (ex. organizacao de projeto).
SUBDIR = 
INC = $(wildcard *.h $(foreach fd, $(SUBDIR), $(fd)/*.h))
SRC = $(wildcard *.c $(foreach fd, $(SUBDIR), $(fd)/*.c))
OBJ = $(SRC:.c=.o)

.PHONY: all clean

all: $(TARGET)

# Comandos especificos para Windows (del, copy).
clean:
	-del /Q /S *.o >NUL 2>&1
	-del /Q /S $(SDL_DLL_FILE) >NUL 2>&1
	-del /Q /S $(SDL_IMAGE_DLL_FILE) >NUL 2>&1
	-del /Q /S $(SDL_TTF_DLL_FILE) >NUL 2>&1
	-del /Q /S $(TARGET).exe >NUL 2>&1

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(INC_DIRS) -o $@ $^ $(LDFLAGS) $(LDLIBS)
	copy $(SDL_DLL_DIR)\\$(SDL_DLL_FILE) .\\$(SDL_DLL_FILE)
	copy $(SDL_IMAGE_DLL_DIR)\\$(SDL_IMAGE_DLL_FILE) .\\$(SDL_IMAGE_DLL_FILE)
	copy $(SDL_TTF_DLL_DIR)\\$(SDL_TTF_DLL_FILE) .\\$(SDL_TTF_DLL_FILE)

%.o: %.c $(INC)
	$(CC) $(CFLAGS) $(INC_DIRS) -c $< -o $@
